# This is a basic workflow to help you get started with Actions

name: Deploy-App-K8s

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: workflow_dispatch

env:
  zone: us-central1-c

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-on-GKE:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    # Get new cluster credentials 
    - run: |-
        gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }}
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm install petclinic-db --set mysqlDatabase=petclinic stable/mysql
        kubectl apply -k kubernetes/petclinic-deployment.yaml
        kubectl apply -f kubernetes/petclinic-svc.yaml

