# This is a basic workflow to help you get started with Actions
#
name: GCP Teardown

on: workflow_dispatch

env:
  zone: us-central1-c

jobs:
  GCP-Kubernetes:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: |-
        gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }}
        kubectl delete -f kubernetes/petclinic-deployment.yaml
        kubectl delete -f kubernetes/petclinic-svc.yaml
        gcloud container clusters delete ${{secrets.GKE_CLUSTER_NAME}} --zone=us-central1-c --quiet
