# This is a basic workflow to help you get started with Actions
name: GCP SetUp

on: workflow_dispatch

env:
  zone: us-central1-c
  machineType: e2-highcpu-4 
  releaseName: datadog-agent  

jobs:
 GCP-create-kubernetes-w-DD:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud container clusters create ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }} --machine-type=${{ env.machineType }}
